name = "usage-panel"
main = "_worker.js"
compatibility_date = "2026-01-10"
keep_vars = true

[triggers]
crons = ["*/15 * * * *"]    # 每15分钟执行一次

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = ""				#KV数据库id